describe('template spec', () => {
  beforeEach(() => {
    cy.visit('')
  })
  it('Success Login', () => {
    // cy.get('.panel > .header > .authorization-link > a').click()
    // cy.get('.login-container > .block-customer-login > .block-title > #block-customer-login-heading').should('be.visible')
    // cy.get('#email').type('wahidazi1st@gmail.com')
    // cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .password > .control > #pass').type('Wa123456')
    // cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
    cy.loginLuma('wahidazi1st@gmail.com','Wa123456')
    cy.get(':nth-child(2) > .greet > .logged-in')
  })
  it('Failed Login - Wrong Email', () => {
    // cy.get('.panel > .header > .authorization-link > a').click()
    // cy.get('.login-container > .block-customer-login > .block-title > #block-customer-login-heading').should('be.visible')
    // cy.get('#email').type('salah@gmail.com')
    // cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .password > .control > #pass').type('Wa123456')
    // cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
    cy.loginLuma('salah@gmail.com','Wa123456')
    cy.get('.message-error > div').should('be.visible')
  })
  it('Failed Login - Wrong Password', () => {
    // cy.get('.panel > .header > .authorization-link > a').click()
    // cy.get('.login-container > .block-customer-login > .block-title > #block-customer-login-heading').should('be.visible')
    // cy.get('#email').type('wahidazi1st@gmail.com')
    // cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .password > .control > #pass').type('salah')
    // cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
    cy.loginLuma('wahidazi1st@gmail.com','salah')
    cy.get('.message-error > div').should('be.visible')
  })
  it('Failed Login - Invalid Email', () => {
    // cy.get('.panel > .header > .authorization-link > a').click()
    // cy.get('.login-container > .block-customer-login > .block-title > #block-customer-login-heading').should('be.visible')
    // cy.get('#email').type('wahidaja')
    // cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .password > .control > #pass').type('Wa123456')
    // cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
    cy.loginLuma('wahidaja','Wa123456')
    cy.get('#email-error').should('contain.text','Please enter a valid email address')
  })
  it('Success Reset Password - Pass forgot password', () => {
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.get('.login-container > .block-customer-login > .block-title > #block-customer-login-heading').should('be.visible')
    cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > .secondary > .action > span').click()
    cy.get('.note').should('be.visible')
    cy.get('#email_address').type('wahidazis1st@gmail.com')
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
    cy.get('.message-success > div').should('be.visible')
  })
})